In [6]:
import numpy as np
import pandas as pd
from math import sin, asin, cos, radians, fabs, sqrt

EARTH_RADIUS = 6371      # 地球平均半径大约6371km


def hav(theta):
    s = sin(theta / 2)
    return s * s


def get_distance_hav(lat0, lng0, lat1, lng1):
    # 用haversine公式计算球面两点间的距离
    # 经纬度转换成弧度
    lat0 = radians(lat0)
    lat1 = radians(lat1)
    lng0 = radians(lng0)
    lng1 = radians(lng1)
    dlng = fabs(lng0 - lng1)
    dlat = fabs(lat0 - lat1)
    h = hav(dlat) + cos(lat0) * cos(lat1) * hav(dlng)
    distance = 2 * EARTH_RADIUS * asin(sqrt(h))      # km
    return distance

def gaussian_kernel(lat0, lng0, lat1, lng1, sigma):
    distance_hav = get_distance_hav(lat0, lng0, lat1, lng1)
    distance = np.linalg.norm(distance_hav)
    print(distance)
    similarity = np.exp(-distance**2 / (2* (sigma**2)))
    print(similarity)
    print('\n')
    return similarity

def compute_similarity_matrix(X,sigma):
    n = X.shape[0]
    S = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            lat0=X[i,1]
            lng0=X[i,0]
            lat1=X[j,1]
            lng1=X[j,0]
            print(lat0)
            print(lng0)
            print(lat1)
            print(lng1)
            S[i,j] = gaussian_kernel(lat0, lng0, lat1, lng1, sigma)
    return S

In [7]:
df=pd.DataFrame(pd.read_excel(r'D:\myJupyter\ST-GK-Tensorflow\data_adj\Gauss03.xlsx',usecols=['longitude','latitude']))
df=df.values
print(df)

[[117.759507  29.055341]
 [117.759507  29.055341]
 [117.759507  29.055341]
 [117.762141  29.054945]
 [117.762141  29.054945]
 [117.762141  29.054945]
 [117.764688  29.054473]
 [117.764688  29.054473]
 [117.764688  29.054473]
 [117.76552   29.054306]
 [117.76552   29.054306]
 [117.76552   29.054306]
 [117.76328   29.058546]
 [117.76328   29.058546]
 [117.76328   29.058546]
 [117.761372  29.059201]
 [117.761372  29.059201]
 [117.761372  29.059201]
 [117.765532  29.058046]
 [117.765532  29.058046]
 [117.765532  29.058046]
 [117.763673  29.059484]
 [117.763673  29.059484]
 [117.763673  29.059484]
 [117.764007  29.060376]
 [117.764007  29.060376]
 [117.764007  29.060376]
 [117.76424   29.061048]
 [117.76424   29.061048]
 [117.76424   29.061048]]


In [11]:
X = df
distance=[]
n = X.shape[0]
for i in range(n):
    for j in range(n):
        lat0=X[i,1]
        lng0=X[i,0]
        lat1=X[j,1]
        lng1=X[j,0]
        distance.append(get_distance_hav(lat0, lng0, lat1, lng1))
print(distance)
sigma=np.std(distance)
sigma

[0.0, 0.0, 0.0, 0.259787289731521, 0.259787289731521, 0.259787289731521, 0.5127668731333169, 0.5127668731333169, 0.5127668731333169, 0.5956964317366007, 0.5956964317366007, 0.5956964317366007, 0.5113712433663101, 0.5113712433663101, 0.5113712433663101, 0.46592334791940926, 0.46592334791940926, 0.46592334791940926, 0.6583552705068345, 0.6583552705068345, 0.6583552705068345, 0.6133485460207355, 0.6133485460207355, 0.6133485460207355, 0.7104677557566543, 0.7104677557566543, 0.7104677557566543, 0.7837990155706923, 0.7837990155706923, 0.7837990155706923, 0.0, 0.0, 0.0, 0.259787289731521, 0.259787289731521, 0.259787289731521, 0.5127668731333169, 0.5127668731333169, 0.5127668731333169, 0.5956964317366007, 0.5956964317366007, 0.5956964317366007, 0.5113712433663101, 0.5113712433663101, 0.5113712433663101, 0.46592334791940926, 0.46592334791940926, 0.46592334791940926, 0.6583552705068345, 0.6583552705068345, 0.6583552705068345, 0.6133485460207355, 0.6133485460207355, 0.6133485460207355, 0.7104677

0.23113503422626616

In [12]:
X = df
S = compute_similarity_matrix(X, sigma)
S

29.055341
117.759507
29.055341
117.759507
0.0
1.0


29.055341
117.759507
29.055341
117.759507
0.0
1.0


29.055341
117.759507
29.055341
117.759507
0.0
1.0


29.055341
117.759507
29.054945
117.762141
0.259787289731521
0.5317154929955088


29.055341
117.759507
29.054945
117.762141
0.259787289731521
0.5317154929955088


29.055341
117.759507
29.054945
117.762141
0.259787289731521
0.5317154929955088


29.055341
117.759507
29.054473
117.764688
0.5127668731333169
0.08536563897008151


29.055341
117.759507
29.054473
117.764688
0.5127668731333169
0.08536563897008151


29.055341
117.759507
29.054473
117.764688
0.5127668731333169
0.08536563897008151


29.055341
117.759507
29.054306
117.76552
0.5956964317366007
0.0361112927090586


29.055341
117.759507
29.054306
117.76552
0.5956964317366007
0.0361112927090586


29.055341
117.759507
29.054306
117.76552
0.5956964317366007
0.0361112927090586


29.055341
117.759507
29.058546
117.76328
0.5113712433663101
0.08651526971599477


29.055341
117.759507
29.058

array([[1.        , 1.        , 1.        , 0.53171549, 0.53171549,
        0.53171549, 0.08536564, 0.08536564, 0.08536564, 0.03611129,
        0.03611129, 0.03611129, 0.08651527, 0.08651527, 0.08651527,
        0.13110765, 0.13110765, 0.13110765, 0.01730827, 0.01730827,
        0.01730827, 0.02957294, 0.02957294, 0.02957294, 0.00887792,
        0.00887792, 0.00887792, 0.00318362, 0.00318362, 0.00318362],
       [1.        , 1.        , 1.        , 0.53171549, 0.53171549,
        0.53171549, 0.08536564, 0.08536564, 0.08536564, 0.03611129,
        0.03611129, 0.03611129, 0.08651527, 0.08651527, 0.08651527,
        0.13110765, 0.13110765, 0.13110765, 0.01730827, 0.01730827,
        0.01730827, 0.02957294, 0.02957294, 0.02957294, 0.00887792,
        0.00887792, 0.00887792, 0.00318362, 0.00318362, 0.00318362],
       [1.        , 1.        , 1.        , 0.53171549, 0.53171549,
        0.53171549, 0.08536564, 0.08536564, 0.08536564, 0.03611129,
        0.03611129, 0.03611129, 0.08651527, 0.

In [13]:
np.fill_diagonal(S,0)
S

array([[0.        , 1.        , 1.        , 0.53171549, 0.53171549,
        0.53171549, 0.08536564, 0.08536564, 0.08536564, 0.03611129,
        0.03611129, 0.03611129, 0.08651527, 0.08651527, 0.08651527,
        0.13110765, 0.13110765, 0.13110765, 0.01730827, 0.01730827,
        0.01730827, 0.02957294, 0.02957294, 0.02957294, 0.00887792,
        0.00887792, 0.00887792, 0.00318362, 0.00318362, 0.00318362],
       [1.        , 0.        , 1.        , 0.53171549, 0.53171549,
        0.53171549, 0.08536564, 0.08536564, 0.08536564, 0.03611129,
        0.03611129, 0.03611129, 0.08651527, 0.08651527, 0.08651527,
        0.13110765, 0.13110765, 0.13110765, 0.01730827, 0.01730827,
        0.01730827, 0.02957294, 0.02957294, 0.02957294, 0.00887792,
        0.00887792, 0.00887792, 0.00318362, 0.00318362, 0.00318362],
       [1.        , 1.        , 0.        , 0.53171549, 0.53171549,
        0.53171549, 0.08536564, 0.08536564, 0.08536564, 0.03611129,
        0.03611129, 0.03611129, 0.08651527, 0.

In [14]:
df = pd.DataFrame(S)
df.to_excel(r'D:\myJupyter\ST-GK-Tensorflow\data_adj\Gausss+sigma_adj.xlsx')